
<div class="container theme-showcase" role="main">
  <div class="jumbotron">
	<h2>Welcome to Krystal Framework!</h2>
	<p><a href="#" class="btn btn-primary btn-lg" role="button">Check out the repository &raquo;</a></p>
  </div>
  
  <div class="row">
	<div class="col-lg-4">
	  <h2>Simple and nice API</h2>
	  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
	</div>
	
	<div class="col-lg-4">
	  <h2>Easy to use and extend</h2>
	  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
   </div>
	
	<div class="col-lg-4">
	  <h2>Heading</h2>
	  <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
	</div>
  </div>
</div>
